export const BUILD_MANIFEST = {
  version: "2.4.4",
  project: "University of Babylon Pediatric Virtual Clinical Simulation",
  status: "RELEASE_CANDIDATE",
  architecture: {
    clinicalCore: true,
    scenarioEngine: true,
    safetyEngine: true,
    cjmmAudit: true,
    sbarDebrief: true,
    threeJsScene: true,
    touchInteraction: true,
    clinicalVisualBridge: true,
    audioStateBridge: true,
    audioValidationRegistry: true,
    performanceMonitoring: true,
    ehrModel: true,
    waveformEngine: true,
    twoBoneIK: true,
    assetRegistry: true,
    procedureStateMachine: true,
    elevenScenarioPackages: true,
    integratedScenarioAssessment: true,
    scenarioClinicalTraceability: true,
  },
  validationPolicy: {
    noSilentClinicalCorrection: true,
    noRandomPhysiology: true,
    visualLayerCannotMutatePhysiology: true,
    medicationDoseExecutionRequiresValidatedOrderSet: true,
    timedEventsRequireExplicitSourceTiming: true,
  },
} as const;
